### ISSUE TITLE
Improve contact details view

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#3306]
![image](https://user-images.githubusercontent.com/52440189/231748464-39cc019e-a317-45e1-a271-65001583a94c.png)
![image](https://user-images.githubusercontent.com/52440189/231748352-ba00dde3-3987-416a-aab0-ae86f928b256.png)

Mobile view:
![image](https://user-images.githubusercontent.com/52440189/231755324-1cc257a8-bd1e-427f-b806-38f778900c16.png)

- [ ] Single column layout #3305
- [ ] Improved `Add new property` #3304 
- [ ] View mode has quick actions and shared items 
- [ ] Uses vue components 
- [ ] Switch between view and edit mode should not cause jumping around of text. The text is placed such that on changing to edit mode, the position of the text itself changes as little as possible, and only a border appears around the text indicating an input field.
- [ ] Switching between view and edit mode should not change the position of the Edit/save button either, esp. in mobile
- [ ] MDI icons for each property mentioned in [#3304](https://github.com/nextcloud/contacts/issues/3304)

_Originally posted by @nimishavijay in https://github.com/nextcloud/contacts/issues/1923#issuecomment-1506870070_
